default: &default
  adapter: :postgresql
  encoding: unicode
  host: localhost
  port: 5433
  user: peg


development:
<<: *default
database: to_do_development


test:
<<: *default
database: to_do_test

